In [2]:
import pandas as pd
df=pd.read_excel('C:\\Users\dell\FSDS\datafsds\Attribute DataSet.xlsx')

In [6]:
df.to_csv('Attribute DataSet1.csv',index=False)

In [7]:
pd.read_csv('Attribute DataSet1.csv')

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [8]:
import mysql.connector as con
import csv
con.connect(host='localhost',user='root',password='0000')

In [7]:
curspr=con.cursor()

TypeError: 'module' object is not callable

In [9]:
import mysql.connector as con

In [23]:
conn=con.connect(host='localhost',user='root',password='0000')

In [27]:
query='Create database Task1'

In [28]:
cursor=conn.cursor()

In [26]:
for i in cursor.fetchall():
    print(i)

InterfaceError: No result set to fetch from

In [29]:
cursor.execute(query)

In [30]:
for i in cursor.fetchall():
    print(i)

In [35]:
import mysql.connector as connection
try:
    con=connection.connect(host='localhost',user='root',password='0000')
    print(con.is_connected())
    query='Drop database Task1;'
    
    cur=con.cursor()
    cur.execute(query)
    
except Exception as e:
    con.close()
    print(str(e))

True

In [ ]:
MySql : 1. Create A table for attribute Dat Set And Dress Data Set
    2.Do a bulk load for these two table for respective dataset 
    3.read these dataset in pandas as a dataframe 
    4.Convert attribute dataset in json Format 
    5.Store this dataset into mongodb 
    6.In SQL task try to perform left join operation with attribute datset and dress dataset on DressId 
    7.Write a sql quey to find out how many unique dress we have based on Dress id 
    8. Try to find out how many dress is having recommendation 0 
    9.Try to find out a third highest most selling Dress

In [37]:
import pandas as pd
import mysql.connector as conn
import csv

con=conn.connect(host='localhost',user='root',password='0000',database='Task')
cursor=con.cursor()
query="Create Table Attribute_DataSet(Dress_ID int(30),Style varchar(10),Price varchar(10),Rating float(3,1),Size char(5),Season varchar(20),NeckLine varchar(20),SleeveLength varchar(10),waiseline varchar(20),Material varchar(20),FabricType varchar(20),Decoration varchar(20),Pattern_Type varchar(20),Recommendation int(10));"

cursor.execute()

In [43]:
data=open('Attribute DataSet1.csv','r')
next(data)
data_csv=csv.reader(data,delimiter=',')
print(data_csv)
for i in enumerate(data_csv):
    for j in i[i]:
        cursor.execute('insert into Task.Attribute_DataSet values({data})'.format(data=(j)))
print('All Data Inserted Successfully')
con.commit()

<_csv.reader object at 0x0000023DD2AC3DC0>

TypeError: tuple indices must be integers or slices, not tuple

In [18]:
import mysql.connector
from mysql.connector import Error
from sqlalchemy import create_engine
import pandas as pd

In [3]:
host_name='localhost'
user_name='root'
user_password='0000'
db_name='Task'
port_num=3306

In [63]:
engine=create_engine("mysql+pymysql://root:0000@localhost/Task")

In [64]:
my_df=pd.read_csv('Attribute DataSet2.csv')
my_df.to_sql(name='Attribute_DataSet',con=engine,if_exists='append',index=False)

OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'Pattern Type' in 'field list'")
[SQL: INSERT INTO `Attribute_DataSet` (`Dress_ID`, `Style`, `Price`, `Rating`, `Size`, `Season`, `NeckLine`, `SleeveLength`, waiseline, `Material`, `FabricType`, `Decoration`, `Pattern Type`, `Recommendation`) VALUES (%(Dress_ID)s, %(Style)s, %(Price)s, %(Rating)s, %(Size)s, %(Season)s, %(NeckLine)s, %(SleeveLength)s, %(waiseline)s, %(Material)s, %(FabricType)s, %(Decoration)s, %(Pattern Type)s, %(Recommendation)s)]
[parameters: ({'Dress_ID': 1006032852, 'Style': 'Sexy', 'Price': 'Low', 'Rating': 4.6, 'Size': 'M', 'Season': 'Summer', 'NeckLine': 'o-neck', 'SleeveLength': 'sleevless', 'waiseline': 'empire', 'Material': 'silk', 'FabricType': 'chiffon', 'Decoration': 'ruffles', 'Pattern Type': 'animal', 'Recommendation': 1}, {'Dress_ID': 1212192089, 'Style': 'Casual', 'Price': 'Low', 'Rating': 0.0, 'Size': 'L', 'Season': 'Summer', 'NeckLine': 'o-neck', 'SleeveLength': 'Petal', 'waiseline': 'natural', 'Material': 'microfiber', 'FabricType': 'Data Missing', 'Decoration': 'ruffles', 'Pattern Type': 'animal', 'Recommendation': 0}, {'Dress_ID': 1190380701, 'Style': 'vintage', 'Price': 'High', 'Rating': 0.0, 'Size': 'L', 'Season': 'Automn', 'NeckLine': 'o-neck', 'SleeveLength': 'full', 'waiseline': 'natural', 'Material': 'polyster', 'FabricType': 'Data Missing', 'Decoration': 'Data Missing', 'Pattern Type': 'print', 'Recommendation': 0}, {'Dress_ID': 966005983, 'Style': 'Brief', 'Price': 'Average', 'Rating': 4.6, 'Size': 'L', 'Season': 'Spring', 'NeckLine': 'o-neck', 'SleeveLength': 'full', 'waiseline': 'natural', 'Material': 'silk', 'FabricType': 'chiffon', 'Decoration': 'embroidary', 'Pattern Type': 'print', 'Recommendation': 1}, {'Dress_ID': 876339541, 'Style': 'cute', 'Price': 'Low', 'Rating': 4.5, 'Size': 'M', 'Season': 'Summer', 'NeckLine': 'o-neck', 'SleeveLength': 'butterfly', 'waiseline': 'natural', 'Material': 'chiffonfabric', 'FabricType': 'chiffon', 'Decoration': 'bow', 'Pattern Type': 'dot', 'Recommendation': 0}, {'Dress_ID': 1068332458, 'Style': 'bohemian', 'Price': 'Low', 'Rating': 0.0, 'Size': 'M', 'Season': 'Summer', 'NeckLine': 'v-neck', 'SleeveLength': 'sleevless', 'waiseline': 'empire', 'Material': 'chiffonfabric', 'FabricType': 'Data Missing', 'Decoration': 'Data Missing', 'Pattern Type': 'print', 'Recommendation': 0}, {'Dress_ID': 1220707172, 'Style': 'Casual', 'Price': 'Average', 'Rating': 0.0, 'Size': 'XL', 'Season': 'Summer', 'NeckLine': 'o-neck', 'SleeveLength': 'full', 'waiseline': 'Data Missing', 'Material': 'cotton', 'FabricType': 'Data Missing', 'Decoration': 'Data Missing', 'Pattern Type': 'solid', 'Recommendation': 0}, {'Dress_ID': 1219677488, 'Style': 'Novelty', 'Price': 'Average', 'Rating': 0.0, 'Size': 'free', 'Season': 'Automn', 'NeckLine': 'o-neck', 'SleeveLength': 'short', 'waiseline': 'natural', 'Material': 'polyster', 'FabricType': 'broadcloth', 'Decoration': 'lace', 'Pattern Type': 'Data Missing', 'Recommendation': 0}  ... displaying 10 of 500 total bound parameter sets ...  {'Dress_ID': 655464934, 'Style': 'Casual', 'Price': 'Average', 'Rating': 4.6, 'Size': 'L', 'Season': 'winter', 'NeckLine': 'boat-neck', 'SleeveLength': 'sleevless', 'waiseline': 'empire', 'Material': 'silk', 'FabricType': 'broadcloth', 'Decoration': 'applique', 'Pattern Type': 'print', 'Recommendation': 1}, {'Dress_ID': 919930954, 'Style': 'Casual', 'Price': 'Low', 'Rating': 4.4, 'Size': 'free', 'Season': 'Summer', 'NeckLine': 'v-neck', 'SleeveLength': 'short', 'waiseline': 'empire', 'Material': 'cotton', 'FabricType': 'Corduroy', 'Decoration': 'lace', 'Pattern Type': 'solid', 'Recommendation': 0})]
(Background on this error at: http://sqlalche.me/e/14/e3q8)

In [13]:
!pip install pymysql

Requirement already satisfied: pymysql in c:\users\dell\anaconda3\anaconda\lib\site-packages (1.0.2)

In [23]:
my_df['Material'].fillna(method ='ffill',inplace=True)

In [25]:
my_df.fillna(my_df.mean())

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [27]:
my_df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [32]:
my_df['Material'].fillna('silk',inplace=True)

In [33]:
my_df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,silk,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [34]:
my_df['FabricType'].fillna('Data Missing',inplace=True)

In [35]:
my_df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,silk,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,Data Missing,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,Data Missing,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,Data Missing,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,Data Missing,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,Data Missing,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [59]:
#my_df['Pattern Type'].fillna('Data Missing',inplace=True)
my_df[my_df['Recommendation'].isnull()]

Empty DataFrame
Columns: [Dress_ID, Style, Price, Rating, Size, Season, NeckLine, SleeveLength, waiseline, Material, FabricType, Decoration, Pattern Type, Recommendation]
Index: []

In [61]:
my_df.to_csv('Attribute DataSet2.csv',index=False)